bump up memory golds and make sure and throw an error if a build fails in the pipeline

diff --git a/.github/actions/build-action/action.yaml b/.github/actions/build-action/action.yaml
--- a/.github/actions/build-action/action.yaml
+++ b/.github/actions/build-action/action.yaml
@@ -44,4 +44,10 @@ runs:
 
     - name: Build project
       shell: bash
-      run: python3 ./.github/actions/build-action/build.py --ip ${{ inputs.VM_IP }} --username ${{ inputs.VM_USERNAME }} --build-type ${{ inputs.build-type }} --gpu ${{ inputs.gpu }} --code-coverage ${{ inputs.code-coverage }} --protego ${{ inputs.with-protego }}
+      run: |
+        python3 ./.github/actions/build-action/build.py --ip ${{ inputs.VM_IP }} --username ${{ inputs.VM_USERNAME }} --build-type ${{ inputs.build-type }} --gpu ${{ inputs.gpu }} --code-coverage ${{ inputs.code-coverage }} --protego ${{ inputs.with-protego }}
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          echo "Build failed with exit code $exit_code"
+          exit $exit_code
+        fi
