update dockers to have protego

diff --git a/docker/Dockerfile_AperiMech_Ubuntu2404_Nvidia b/docker/Dockerfile_AperiMech_Ubuntu2404_Nvidia
--- a/docker/Dockerfile_AperiMech_Ubuntu2404_Nvidia
+++ b/docker/Dockerfile_AperiMech_Ubuntu2404_Nvidia
@@ -1,3 +1,5 @@
+# syntax=docker/dockerfile:1.4
+
 # Dockerfile for building a GPU-enabled environment for the aperi-mech project on Ubuntu 24.04
 
 # Base image with CUDA support. Note that cuda 12.8 had ncurses linking issues in Trilinos/SEACAS/Aprepro
@@ -15,6 +17,9 @@ ARG CUDA_ARCH=75
 # Define the user and group id
 ARG USER_ID=1000
 ARG GROUP_ID=1000
+
+# Add build arg for protego (ssh submodules)
+ARG PROTEGO=0
 
 # Validate CUDA_ARCH input
 RUN if ! [[ "$CUDA_ARCH" =~ ^[0-9]+$ ]]; then \
@@ -142,9 +147,6 @@ USER root
 # Configure passwordless sudo for the user
 RUN echo "aperi-mech_docker ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
 
-# Change to the new user
-USER aperi-mech_docker
-
 # Make the working directory
 WORKDIR /home/aperi-mech_docker
 
@@ -154,19 +156,47 @@ ENV HOME=/home/aperi-mech_docker
 # Set the default command to bash
 CMD ["/bin/bash"]
 
+# Clone the public repo by default (for open source users)
 RUN git clone https://github.com/aperijake/aperi-mech.git ${HOME}/aperi-mech
+
+# Fail early if PROTEGO is enabled but no SSH agent is detected
+RUN --mount=type=ssh \
+    if [ "$PROTEGO" = "1" ]; then \
+      if [ ! -S "$SSH_AUTH_SOCK" ]; then \
+        echo "PROTEGO enabled but no SSH agent detected. Failing build."; \
+        exit 1; \
+      fi; \
+    fi
+
+# Add GitHub to known_hosts to avoid host key verification errors
+RUN mkdir -p /root/.ssh && \
+    ssh-keyscan github.com >> /root/.ssh/known_hosts
+
+# Optionally update submodules if SSH agent is available and PROTEGO is set
+RUN --mount=type=ssh \
+    if [ "$PROTEGO" = "1" ]; then \
+      cd ${HOME}/aperi-mech && \
+      echo "PROTEGO enabled and SSH agent detected. Updating submodules with SSH..."; \
+      git submodule update --init --recursive; \
+    else \
+      echo "PROTEGO not enabled. Skipping submodule update."; \
+    fi
+
+# Ensure the aperi-mech directory is owned by the aperi-mech user
+RUN chown -R aperi-mech_docker:aperi-mech_docker ${HOME}/aperi-mech
+
+# Change to the new user
+USER aperi-mech_docker
 
 # Change to the cloned repository directory
 WORKDIR ${HOME}/aperi-mech
-
-# Set the aperi_mech environment variable globally
-ENV aperi_mech=${HOME}/aperi-mech
 
 # Check out the specific branch for spack updates
 RUN git fetch --all && \
     git checkout main
 
-# Set Fortran compiler environment variables globally
+# Set Fortran compiler and aperi-mech environment variables globally
+ENV aperi_mech=${HOME}/aperi-mech
 ENV FC=/usr/bin/gfortran 
 ENV F77=/usr/bin/gfortran
 
@@ -188,18 +218,16 @@ RUN mkdir -p $aperi_mech/venv/src && \
 
 # Configure the Spack environment
 RUN . ./venv/bin/activate && \
-    source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
     spack compiler find && \
     spack external find && \
     spack external find cmake hwloc libxml2 pkgconf bzip2 lz4 snappy zstd libaec ncurses openblas autoconf automake libtool
 
 # Patch Spack for Trilinos support
 RUN . ./venv/bin/activate && \
-    source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
     spack patch-trilinos
 
 # Manually add CUDA to Spack packages.yaml
-RUN . $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
+RUN . ./venv/bin/activate && \
     CUDA_VER=$(nvcc --version | grep "release" | sed 's/.*release //' | awk '{print $1}' | cut -d',' -f1) && \
     mkdir -p ~/.spack && \
     echo "  cuda:" >> ~/.spack/packages.yaml && \
@@ -210,23 +238,23 @@ RUN . $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
 
 # Create a Spack environment for aperi-mech and install it
 RUN . ./venv/bin/activate && \
-    source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
     spack env create aperi-mech && \
     spack -e aperi-mech develop --path $aperi_mech aperi-mech && \
-    spack -e aperi-mech add aperi-mech +cuda cuda_arch=${CUDA_ARCH} build_type=Release && \
+    if [ "$PROTEGO" = "1" ]; then \
+      spack -e aperi-mech add aperi-mech +protego +cuda cuda_arch=${CUDA_ARCH} build_type=Release; \
+    else \
+      spack -e aperi-mech add aperi-mech +cuda cuda_arch=${CUDA_ARCH} build_type=Release; \
+    fi && \
     spack -e aperi-mech concretize -f
 
 # Just breaking up and installing the dependencies in a few steps to give a docker build cache
 RUN . ./venv/bin/activate && \
-    source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
     spack -e aperi-mech install eigen yaml-cpp googletest
 
 RUN . ./venv/bin/activate && \
-    source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
     spack -e aperi-mech install kokkos kokkos-kernels compadre
 
 RUN . ./venv/bin/activate && \
-    source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
     spack -e aperi-mech install trilinos
 
 ## This step is currently failing when it tries to test run an executable as part of the build process
@@ -236,7 +264,6 @@ RUN . ./venv/bin/activate && \
 ##       - source the virtual environment: source $aperi_mech/venv/bin/activate
 ##       - install aperi-mech: spack -e aperi-mech install aperi-mech
 # RUN . ./venv/bin/activate && \
-#     source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
 #     spack -e aperi-mech install aperi-mech
 
 # Set environment variables for aperi-mech
@@ -245,7 +272,6 @@ ENV APERI_MECH_GPU_ENV="aperi-mech"
 
 # Register the local aperi-mech Spack repository so the aperi-mech repo can be found for future builds
 RUN . ./venv/bin/activate && \
-    source $aperi_mech/venv/src/spack/share/spack/setup-env.sh && \
     spack -e aperi-mech repo add $aperi_mech/tools/python/spackx/src/spackx/repos/aperi/
 
 # When running the container, first do: source $aperi_mech/venv/bin/activate
