add performance tests and associated workflow

diff --git a/.github/actions/run-gtest-performance-tests/action.yaml b/.github/actions/run-gtest-performance-tests/action.yaml
--- a/.github/actions/run-gtest-performance-tests/action.yaml
+++ b/.github/actions/run-gtest-performance-tests/action.yaml
@@ -1,5 +1,5 @@
-name: Run regression tests
-description: Run regression tests on the VM, inside the Docker container
+name: Run gtest performance tests
+description: Run gtest performance tests on the VM, inside the Docker container
 inputs:
   VM_IP:
     description: IP address of the VM
@@ -10,11 +10,11 @@ inputs:
   VM_USERNAME:
     description: Username for the VM
     required: true
-  gpu:
-    description: Run GPU tests
+  build-type:
+    description: Build type (e.g., Release, Debug)
     required: true
-  parallel:
-    description: Run parallel tests
+  gpu:
+    description: GPU build
     required: true
 runs:
   using: composite
@@ -22,10 +22,10 @@ runs:
     - name: Print inputs for debugging
       shell: bash
       run: |
+        echo "build-type: ${{ inputs.build-type }}"
         echo "gpu: ${{ inputs.gpu }}"
-        echo "parallel: ${{ inputs.parallel }}"
 
-    - name: Run utils modules tests
+    - name: Run gtest performance tests
       shell: bash
       run: |
         ssh -T -o ConnectTimeout=10 ${{ inputs.VM_USERNAME }}@${{ inputs.VM_IP }} << 'EOF'
@@ -42,29 +42,22 @@ runs:
           echo "On VM, Service name: $service_name"
 
           docker-compose -f $compose_file run --rm $service_name /bin/bash -c '
-            test_flags=""
+            build_path=~/aperi-mech/build/${{ inputs.build-type }}
             if [ ${{ inputs.gpu }} == "true" ]; then
-              test_flags="$test_flags --gpu"
-            else
-              test_flags="$test_flags --cpu"
-            fi
-            if [ ${{ inputs.parallel }} == "true" ]; then
-              test_flags="$test_flags --parallel"
-            else
-              test_flags="$test_flags --serial"
+              build_path=~/aperi-mech/build/${{ inputs.build-type }}_gpu
             fi
             # Debugging
+            echo "In container, inputs.build-type: ${{ inputs.build-type }}"
             echo "In container, inputs.gpu: ${{ inputs.gpu }}"
-            echo "In container, inputs.parallel: ${{ inputs.parallel }}"
-            echo "In container, test_flags: $test_flags"
+            echo "In container, build_path: $build_path"
 
+            cd $build_path
             echo "Setting up Spack environment..."
             . ~/spack/share/spack/setup-env.sh
             spack env activate aperi-mech
 
-            echo "Running regression tests..."
-            cd ~/aperi-mech/test/
-            ./run_regression_tests.py --directory ./regression_tests --build-dir ~/aperi-mech/build/ $test_flags
+            echo "Running gtest performance tests..."
+            ./performance_tests
 
-          '  || { echo "Regression test step failed"; exit 1; }
+          '  || { echo "Gtest performance test step failed"; exit 1; }
         EOF
