with common action working, turn other builds back on

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -107,6 +107,66 @@ jobs:
           VM_USERNAME: ${{ secrets.VM_USERNAME }}
           gpu: false
 
+  build-debug:
+    name: Build Debug
+    runs-on: ubuntu-latest
+    needs: setup
+    concurrency:
+      group: build-and-test-vm-ci-cd
+      cancel-in-progress: false
+    steps:
+      - name: Checkout code # Just to get required actions in .github/
+        uses: actions/checkout@v4
+
+      - name: Build Debug
+        uses: ./.github/actions/build-action
+        with:
+          build-type: Debug
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          VM_USERNAME: ${{ secrets.VM_USERNAME }}
+          gpu: false
+
+  build-release-gpu:
+    name: Build Release, GPU
+    runs-on: ubuntu-latest
+    needs: [setup, build-release, test-release]
+    concurrency:
+      group: build-and-test-vm-ci-cd
+      cancel-in-progress: false
+    steps:
+      - name: Checkout code # Just to get required actions in .github/
+        uses: actions/checkout@v4
+
+      - name: Build Release, GPU
+        uses: ./.github/actions/build-action
+        with:
+          build-type: Release
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          VM_USERNAME: ${{ secrets.VM_USERNAME }}
+          gpu: true
+
+  build-debug-gpu:
+    name: Build Debug, GPU
+    runs-on: ubuntu-latest
+    needs: [setup, build-debug, test-debug]
+    concurrency:
+      group: build-and-test-vm-ci-cd
+      cancel-in-progress: false
+    steps:
+      - name: Checkout code # Just to get required actions in .github/
+        uses: actions/checkout@v4
+
+      - name: Build Debug, GPU
+        uses: ./.github/actions/build-action
+        with:
+          build-type: Debug
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          VM_USERNAME: ${{ secrets.VM_USERNAME }}
+          gpu: true
+
   test-release:
     name: Test Release
     runs-on: ubuntu-latest
@@ -174,212 +234,98 @@ jobs:
             ' || { echo "Unit tests in parallel step failed"; exit 1; }
           EOF
 
-  # build-debug:
-  #   name: Build Debug
-  #   runs-on: ubuntu-latest
-  #   needs: setup
-  #   concurrency:
-  #     group: build-and-test-vm-ci-cd
-  #     cancel-in-progress: false
-  #   steps:
-  #     - name: Checkout code # Just to get required actions in .github/
-  #       uses: actions/checkout@v4
+  test-debug:
+    name: Test Debug
+    runs-on: ubuntu-latest
+    needs: [setup, build-debug]
+    concurrency:
+      group: build-and-test-vm-ci-cd
+      cancel-in-progress: false
+    steps:
+      - name: Checkout code # Just to get required actions in .github/
+        uses: actions/checkout@v4
 
-  #     - name: Common SSH and Azure CLI Setup
-  #       uses: ./.github/actions/common-steps
-  #       with:
-  #         VM_IP: ${{ secrets.VM_IP }}
-  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+      - name: Common SSH and Azure CLI Setup
+        uses: ./.github/actions/common-steps
+        with:
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
-  #     - name: Build project, Debug
-  #       run: |
-  #         ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
-  #           cd ~/aperi-mech
-  #           docker-compose -f docker-compose.yml run --rm aperi-mech-development /bin/bash -c '
-  #             cd ~/aperi-mech
-  #             echo "Setting up Spack environment..."
-  #             . ~/spack/share/spack/setup-env.sh
+      - name: Run unit tests, Debug
+        run: |
+          ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            cd ~/aperi-mech
+            docker-compose -f docker-compose.yml run --rm aperi-mech-development /bin/bash -c '
+              cd ~/aperi-mech/build/Debug
+              make run_all_unit_tests
+            '  || { echo "Unit tests step failed"; exit 1; }
+          EOF
 
-  #             echo "Configuring project..."
-  #             ./do_configure --build-type Debug
+      - name: Run unit tests in parallel, Debug
+        run: |
+          ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            cd ~/aperi-mech
+            docker-compose -f docker-compose.yml run --rm aperi-mech-development /bin/bash -c '
+              cd ~/aperi-mech/build/Debug
+              . ~/spack/share/spack/setup-env.sh
+              spack env activate aperi-mech
+              mpirun -np 3 ./unit_tests
+            ' || { echo "Unit tests in parallel step failed"; exit 1; }
+          EOF
 
-  #             echo "Building project..."
-  #             cd build/Debug
-  #             make clean
-  #             make -j 4
-  #           '  || { echo "Build project step failed"; exit 1; }
-  #         EOF
+  test-release-gpu:
+    name: Test Release, GPU
+    runs-on: ubuntu-latest
+    needs: [setup, build-release-gpu]
+    concurrency:
+      group: build-and-test-vm-ci-cd
+      cancel-in-progress: false
+    steps:
+      - name: Checkout code # Just to get required actions in .github/
+        uses: actions/checkout@v4
 
-  # test-debug:
-  #   name: Test Debug
-  #   runs-on: ubuntu-latest
-  #   needs: [setup, build-debug]
-  #   concurrency:
-  #     group: build-and-test-vm-ci-cd
-  #     cancel-in-progress: false
-  #   steps:
-  #     - name: Checkout code # Just to get required actions in .github/
-  #       uses: actions/checkout@v4
+      - name: Common SSH and Azure CLI Setup
+        uses: ./.github/actions/common-steps
+        with:
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
-  #     - name: Common SSH and Azure CLI Setup
-  #       uses: ./.github/actions/common-steps
-  #       with:
-  #         VM_IP: ${{ secrets.VM_IP }}
-  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+      - name: Run unit tests, GPU
+        run: |
+          ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            cd ~/aperi-mech
+            docker-compose -f docker-compose_nvidia_t4_gpu.yml run --rm aperi-mech-gpu-development /bin/bash -c '
+              cd ~/aperi-mech/build/Release_gpu
+              make run_all_unit_tests
+            '  || { echo "Unit tests step failed"; exit 1; }
+          EOF
 
-  #     - name: Run unit tests, Debug
-  #       run: |
-  #         ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
-  #           cd ~/aperi-mech
-  #           docker-compose -f docker-compose.yml run --rm aperi-mech-development /bin/bash -c '
-  #             cd ~/aperi-mech/build/Debug
-  #             make run_all_unit_tests
-  #           '  || { echo "Unit tests step failed"; exit 1; }
-  #         EOF
+  test-debug-gpu:
+    name: Test Debug, GPU
+    runs-on: ubuntu-latest
+    needs: [setup, build-debug-gpu]
+    concurrency:
+      group: build-and-test-vm-ci-cd
+      cancel-in-progress: false
+    steps:
+      - name: Checkout code # Just to get required actions in .github/
+        uses: actions/checkout@v4
 
-  #     - name: Run unit tests in parallel, Debug
-  #       run: |
-  #         ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
-  #           cd ~/aperi-mech
-  #           docker-compose -f docker-compose.yml run --rm aperi-mech-development /bin/bash -c '
-  #             cd ~/aperi-mech/build/Debug
-  #             . ~/spack/share/spack/setup-env.sh
-  #             spack env activate aperi-mech
-  #             mpirun -np 3 ./unit_tests
-  #           ' || { echo "Unit tests in parallel step failed"; exit 1; }
-  #         EOF
+      - name: Common SSH and Azure CLI Setup
+        uses: ./.github/actions/common-steps
+        with:
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
-  # build-release-gpu:
-  #   name: Build Release, GPU
-  #   runs-on: ubuntu-latest
-  #   needs: [setup, build-release, test-release]
-  #   concurrency:
-  #     group: build-and-test-vm-ci-cd
-  #     cancel-in-progress: false
-  #   steps:
-  #     - name: Checkout code # Just to get required actions in .github/
-  #       uses: actions/checkout@v4
-
-  #     - name: Common SSH and Azure CLI Setup
-  #       uses: ./.github/actions/common-steps
-  #       with:
-  #         VM_IP: ${{ secrets.VM_IP }}
-  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-
-  #     - name: Build project
-  #       run: |
-  #         ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
-  #           cd ~/aperi-mech
-  #           docker-compose -f docker-compose_nvidia_t4_gpu.yml run --rm aperi-mech-gpu-development /bin/bash -c '
-  #             cd ~/aperi-mech
-  #             echo "Setting up Spack environment..."
-  #             . ~/spack/share/spack/setup-env.sh
-
-  #             echo "Configuring project..."
-  #             ./do_configure --gpu --spack-env aperi-mech
-
-  #             echo activate aperi-mech
-  #             spack env activate aperi-mech
-
-  #             echo "Building project..."
-  #             cd build/Release_gpu
-  #             make clean
-  #             make -j 4
-  #           '  || { echo "Build project step failed"; exit 1; }
-  #         EOF
-
-  # test-release-gpu:
-  #   name: Test Release, GPU
-  #   runs-on: ubuntu-latest
-  #   needs: [setup, build-release-gpu]
-  #   concurrency:
-  #     group: build-and-test-vm-ci-cd
-  #     cancel-in-progress: false
-  #   steps:
-  #     - name: Checkout code # Just to get required actions in .github/
-  #       uses: actions/checkout@v4
-
-  #     - name: Common SSH and Azure CLI Setup
-  #       uses: ./.github/actions/common-steps
-  #       with:
-  #         VM_IP: ${{ secrets.VM_IP }}
-  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-
-  #     - name: Run unit tests, GPU
-  #       run: |
-  #         ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
-  #           cd ~/aperi-mech
-  #           docker-compose -f docker-compose_nvidia_t4_gpu.yml run --rm aperi-mech-gpu-development /bin/bash -c '
-  #             cd ~/aperi-mech/build/Release_gpu
-  #             make run_all_unit_tests
-  #           '  || { echo "Unit tests step failed"; exit 1; }
-  #         EOF
-
-  # build-debug-gpu:
-  #   name: Build Debug, GPU
-  #   runs-on: ubuntu-latest
-  #   needs: [setup, build-debug, test-debug]
-  #   concurrency:
-  #     group: build-and-test-vm-ci-cd
-  #     cancel-in-progress: false
-  #   steps:
-  #     - name: Checkout code # Just to get required actions in .github/
-  #       uses: actions/checkout@v4
-
-  #     - name: Common SSH and Azure CLI Setup
-  #       uses: ./.github/actions/common-steps
-  #       with:
-  #         VM_IP: ${{ secrets.VM_IP }}
-  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-
-  #     - name: Build project, Debug, GPU
-  #       run: |
-  #         ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
-  #           cd ~/aperi-mech
-  #           docker-compose -f docker-compose_nvidia_t4_gpu.yml run --rm aperi-mech-gpu-development /bin/bash -c '
-  #             cd ~/aperi-mech
-  #             echo "Setting up Spack environment..."
-  #             . ~/spack/share/spack/setup-env.sh
-
-  #             echo "Configuring project..."
-  #             ./do_configure --gpu --spack-env aperi-mech --build-type Debug
-
-  #             echo activate aperi-mech
-  #             spack env activate aperi-mech
-
-  #             echo "Building project..."
-  #             cd build/Debug_gpu
-  #             make clean
-  #             make -j 4
-  #           '  || { echo "Build project step failed"; exit 1; }
-  #         EOF
-
-  # test-debug-gpu:
-  #   name: Test Debug, GPU
-  #   runs-on: ubuntu-latest
-  #   needs: [setup, build-debug-gpu]
-  #   concurrency:
-  #     group: build-and-test-vm-ci-cd
-  #     cancel-in-progress: false
-  #   steps:
-  #     - name: Checkout code # Just to get required actions in .github/
-  #       uses: actions/checkout@v4
-
-  #     - name: Common SSH and Azure CLI Setup
-  #       uses: ./.github/actions/common-steps
-  #       with:
-  #         VM_IP: ${{ secrets.VM_IP }}
-  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-
-  #     - name: Run unit tests, Debug, GPU
-  #       run: |
-  #         ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
-  #             cd ~/aperi-mech
-  #             docker-compose -f docker-compose_nvidia_t4_gpu.yml run --rm aperi-mech-gpu-development /bin/bash -c '
-  #             cd ~/aperi-mech/build/Debug_gpu
-  #             make run_all_unit_tests
-  #             '  || { echo "Unit tests step failed"; exit 1; }
-  #         EOF
+      - name: Run unit tests, Debug, GPU
+        run: |
+          ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+              cd ~/aperi-mech
+              docker-compose -f docker-compose_nvidia_t4_gpu.yml run --rm aperi-mech-gpu-development /bin/bash -c '
+              cd ~/aperi-mech/build/Debug_gpu
+              make run_all_unit_tests
+              '  || { echo "Unit tests step failed"; exit 1; }
+          EOF
 
   teardown:
     runs-on: ubuntu-latest
@@ -388,12 +334,12 @@ jobs:
         setup,
         build-release,
         test-release,
-        # build-debug,
-        # test-debug,
-        # build-release-gpu,
-        # test-release-gpu,
-        # build-debug-gpu,
-        # test-debug-gpu,
+        build-debug,
+        test-debug,
+        build-release-gpu,
+        test-release-gpu,
+        build-debug-gpu,
+        test-debug-gpu,
       ]
     steps:
       # For debugging purposes
