add gpu runs

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -22,7 +22,7 @@ jobs:
     runs-on: ubuntu-latest
 
     outputs:
-        vm_started: ${{ steps.vm-status.outputs.vm_started }}
+      vm_started: ${{ steps.vm-status.outputs.vm_started }}
 
     steps:
       - name: Checkout code # Just to get required actions in .github/. The actual code checkout is done on the VM
@@ -106,7 +106,7 @@ jobs:
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
             cd ~/aperi-mech
-            docker-compose run --rm ${{ secrets.DOCKER_SERVICE }} /bin/bash -c '
+            docker-compose run --rm aperi-mech:latest -f docker-compose.yml /bin/bash -c '
               cd ~/aperi-mech
               echo "Setting up Spack environment..."
               . ~/spack/share/spack/setup-env.sh
@@ -116,6 +116,42 @@ jobs:
 
               echo "Building project..."
               cd build/Release
+              make clean
+              make -j 4
+            '  || { echo "Build project step failed"; exit 1; }
+          EOF
+
+  build-release-gpu:
+    name: Build Release with GPU support
+    runs-on: ubuntu-latest
+    needs: setup
+    concurrency:
+      group: build-and-test-vm-ci-cd
+      cancel-in-progress: false
+    steps:
+      - name: Checkout code # Just to get required actions in .github/
+        uses: actions/checkout@v4
+
+      - name: Common SSH and Azure CLI Setup
+        uses: ./.github/actions/common-steps
+        with:
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Build project
+        run: |
+          ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            cd ~/aperi-mech
+            docker-compose run --rm aperi-mech-gpu:latest -f docker-compose_nvidia_t4_gpu.yml /bin/bash -c '
+              cd ~/aperi-mech
+              echo "Setting up Spack environment..."
+              . ~/spack/share/spack/setup-env.sh
+
+              echo "Configuring project..."
+              ./do_configure --gpu
+
+              echo "Building project..."
+              cd build/Release_gpu
               make clean
               make -j 4
             '  || { echo "Build project step failed"; exit 1; }
@@ -142,7 +178,7 @@ jobs:
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
             cd ~/aperi-mech
-            docker-compose run --rm ${{ secrets.DOCKER_SERVICE }} /bin/bash -c '
+            docker-compose run --rm aperi-mech:latest -f docker-compose.yml /bin/bash -c '
               cd ~/aperi-mech/build/Release
               make run_all_unit_tests
             '  || { echo "Unit tests step failed"; exit 1; }
@@ -152,8 +188,7 @@ jobs:
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
             cd ~/aperi-mech
-            # docker-compose exec ${{ secrets.DOCKER_SERVICE }} /bin/bash -c '
-            docker-compose run --rm ${{ secrets.DOCKER_SERVICE }} /bin/bash -c '
+            docker-compose run --rm aperi-mech:latest -f docker-compose.yml /bin/bash -c '
               cd ~/aperi-mech/build/Release
               . ~/spack/share/spack/setup-env.sh
               spack env activate aperi-mech
@@ -182,7 +217,7 @@ jobs:
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
             cd ~/aperi-mech
-            docker-compose run --rm ${{ secrets.DOCKER_SERVICE }} /bin/bash -c '
+            docker-compose run --rm aperi-mech:latest -f docker-compose.yml /bin/bash -c '
               cd ~/aperi-mech
               echo "Setting up Spack environment..."
               . ~/spack/share/spack/setup-env.sh
@@ -218,7 +253,7 @@ jobs:
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
             cd ~/aperi-mech
-            docker-compose run --rm ${{ secrets.DOCKER_SERVICE }} /bin/bash -c '
+            docker-compose run --rm aperi-mech:latest -f docker-compose.yml /bin/bash -c '
               cd ~/aperi-mech/build/Debug
               make run_all_unit_tests
             '  || { echo "Unit tests step failed"; exit 1; }
@@ -228,7 +263,7 @@ jobs:
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
             cd ~/aperi-mech
-            docker-compose run --rm ${{ secrets.DOCKER_SERVICE }} /bin/bash -c '
+            docker-compose run --rm aperi-mech:latest -f docker-compose.yml /bin/bash -c '
               cd ~/aperi-mech/build/Debug
               . ~/spack/share/spack/setup-env.sh
               spack env activate aperi-mech
@@ -240,7 +275,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: [setup, build-release, test-release, build-debug, test-debug]
     steps:
-
       # For debugging purposes
       - name: Print VM status
         if: always()
