fix some ci/cd issues

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -72,9 +72,14 @@ jobs:
       - name: Checkout Code on VM
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            set -e # Exit on error
+
             cd ~/aperi-mech
             echo "Fetching git branches..."
             git fetch --all
+
+            echo "Stashing any unstaged changes..."
+            git stash --include-untracked
 
             echo "Checking out main branch and pulling latest changes..."
             git checkout main
diff --git a/.github/workflows/performance-pipeline.yaml b/.github/workflows/performance-pipeline.yaml
--- a/.github/workflows/performance-pipeline.yaml
+++ b/.github/workflows/performance-pipeline.yaml
@@ -74,6 +74,7 @@ jobs:
         if: ${{ github.event_name == 'workflow_dispatch' }}
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            set -e # Exit on error
             cd ~/aperi-mech
             echo "Fetching git branches..."
             git fetch --all
@@ -105,6 +106,7 @@ jobs:
         shell: bash
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            set -e # Exit on error
             cd ~/aperi-mech/build
             echo "Clean existing gtest performance test results..."
             rm -f */performance_*.json performance_*.json
@@ -270,10 +272,22 @@ jobs:
     runs-on: ubuntu-latest
     needs: [setup, performance-test-release, performance-test-release-gpu]
     steps:
+      - name: Checkout Code on Runner # Just to get required actions in .github/. The actual code checkout is done on the VM
+        uses: actions/checkout@v4
+        with:
+          lfs: false
+
+      - name: Common SSH and Azure CLI Setup
+        uses: ./.github/actions/common-steps
+        with:
+          VM_IP: ${{ secrets.VM_IP }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+
       - name: Collect performance test results
         shell: bash
         run: |
           ssh -T -o ConnectTimeout=10 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
+            set -e # Exit on error
             cd ~/aperi-mech
 
             compose_file=docker-compose.yml
